# -*- coding: utf-8 -*-

{
    'name': 'Simpac',
    'version': '0.1',
    'category': 'Sudokeys',
    'sequence': 1,
    'summary': 'Simpac',
    'description': """""",
    'author': 'Sudokeys',
    'website': 'http://www.sudokeys.com',
    'depends': ['sale', 'hr', 'hr_timesheet', 'hr_timesheet_sheet', 'mrp','account', 'product', 'stock'],
    'data': [
        'report/bdx_depot_courrier_en.xml',
        'report/bdx_depot_destineo.xml',
        'security/ir.model.access.csv',
        'security/sale_security.xml',
        'wizard/configurator_view.xml',
        'wizard/timesheet_view.xml',
        'wizard/timesheet_invoice_view.xml',
        'sale_view.xml',
        'mrp_view.xml',
        'product_view.xml',
        'stock_view.xml',
        'hr_view.xml',
        'res_partner_view.xml',
        'report/timesheet.xml',
        'report/sale_report.xml',
        'report/invoice.xml',
        'report/timesheet.xml',
        'edi/timesheet_action_data.xml',
        #~ 'data/simpac_data.xml',
        #~ 'report/report_stock_affran_view.xml',
        
        
        #données
        'data/product.category.csv',
        'data/product.tags.csv',
        'data/product.product.csv',
        'data/mrp.workcenter.csv',
        'data/mrp.routing.csv',
        'data/mrp.routing.workcenter.csv',
        'data/mrp.bom.xml',
    ],
    'js': ['static/src/js/limit_search.js'],
    'demo': [],
    'test': [],
    'installable': True,
    'auto_install': False,
    'application': True,
}
# vim:expandtab:smartindent:tabstop=4:softtabstop=4:shiftwidth=4:
